# Generated by Django 5.1.7 on 2025-05-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
    ]
